// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/nanobox-io/golang-discovery (interfaces: Generator)

package mock_golang_discovery

import (
	gomock "github.com/golang/mock/gomock"
	io "io"
)

// Mock of Generator interface
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *_MockGeneratorRecorder
}

// Recorder for MockGenerator (not exported)
type _MockGeneratorRecorder struct {
	mock *MockGenerator
}

func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &_MockGeneratorRecorder{mock}
	return mock
}

func (_m *MockGenerator) EXPECT() *_MockGeneratorRecorder {
	return _m.recorder
}

func (_m *MockGenerator) New(_param0 string) io.Closer {
	ret := _m.ctrl.Call(_m, "New", _param0)
	ret0, _ := ret[0].(io.Closer)
	return ret0
}

func (_mr *_MockGeneratorRecorder) New(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "New", arg0)
}
